services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis
  orderdb:
    image: mcr.microsoft.com/mssql/server
    
  catalog.api:
    depends_on:
      - catalogdb
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  basket.api:
    depends_on:
      - basketdb
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  discount.grpc:
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
